### ISSUE TITLE
TypeError when opening Find in Files dialog first after IDE loaded

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#498]
The following error occurs when opening Find in Files dialog first after IDE loaded. It seems that focusNode() for the input is called too early before dialog is loaded.

TypeError: Cannot read property 'focusNode' of null(…) "TypeError: Cannot read property 'focusNode' of null
    at handleFindInFiles (https://dev.wsdk.io/common/src/webida/plugins/fs-commands/fs-commands.js:503:25)
    at Object.findInCurDir (https://dev.wsdk.io/common/src/webida/plugins/fs-commands/fs-commands.js:148:13)
    at https://dev.wsdk.io/common/src/webida/plugins/workbench/command-system/MenuItemTree.js:970:54
    at runFactory (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1104:43)
    at execModule (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1232:5)
    at https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1267:6
    at guardCheckComplete (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1247:5)
    at checkComplete (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1262:4)
    at onLoad (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1317:7)
    at Array.load.finish (https://dev.wsdk.io/bower_components/dojo-1.9.7/text.js:189:6)
    at https://dev.wsdk.io/bower_components/dojo-1.9.7/text.js:206:24
    at signalListener (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:37:21)
    at signalWaiting (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:28:4)
    at canceler.resolve (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:192:5)
    at signalDeferred (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:81:15)
    at signalListener (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:52:6)
    ----------------------------------------
    rejected at signalDeferred (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:84:15)
    at signalListener (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:55:5)
    at signalWaiting (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:28:4)
    at canceler.resolve (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:192:5)
    at signalDeferred (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:81:15)
    at signalListener (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:52:6)
    at signalWaiting (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:28:4)
    at canceler.resolve (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:192:5)
    at signalDeferred (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:81:15)
    at signalListener (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:58:4)
    at signalWaiting (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:28:4)
    at canceler.resolve (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:192:5)
    at signalDeferred (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:81:15)
    at signalListener (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:52:6)
    at signalWaiting (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:28:4)
    at canceler.resolve (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:192:5)
    ----------------------------------------
Error
    at Promise.canceler.then.promise.then [as then] (https://dev.wsdk.io/bower_components/dojo-1.9.7/Deferred.js:252:24)
    at getText (https://dev.wsdk.io/bower_components/dojo-1.9.7/text.js:8:72)
    at Object.load (https://dev.wsdk.io/bower_components/dojo-1.9.7/text.js:203:6)
    at injectPlugin (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1321:13)
    at injectModule (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1401:6)
    at forEach (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:93:6)
    at https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:728:5
    at guardCheckComplete (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1247:5)
    at injectDependencies (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:727:4)
    at https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1591:6
    at forEach (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:93:6)
    at runDefQ (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1590:5)
    at onLoadCallback (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1407:6)
    at HTMLScriptElement.req.injectUrl.onLoad (https://dev.wsdk.io/bower_components/dojo-1.9.7/dojo.js:1677:20)"

**Comment by hwshim** [comment]
Please see #546
